drop table if exists task_entries_domain CASCADE;
drop table if exists task_lists_domain CASCADE;
create table task_entries_domain (id bigint generated by default as identity, completed boolean not null, description varchar(255) not null, due_date date not null, my_list_id bigint, primary key (id));
create table task_lists_domain (id bigint generated by default as identity, title varchar(255) not null, primary key (id));
alter table task_entries_domain add constraint FK87dy1e3cw8ouiqibxd8giwmwy foreign key (my_list_id) references task_lists_domain on delete cascade;