CREATE DATABASE IF NOT EXISTS Tasks;


USE Tasks;

SELECT * FROM task;

create table task (id integer generated by default as identity, no_of_hours varchar(255) not null, priority varchar(255) not null, task varchar(255) not null, task_allocation varchar(255) not null, primary key (id));

create table task (id integer generated by default as identity, task varchar(255) not null, primary key (id));
alter table task add constraint UK_4m9ur9dauj0e5sft3dvtsfhdm unique (task);
create table task (id integer generated by default as identity, task varchar(255) not null, primary key (id));
alter table task add constraint UK_4m9ur9dauj0e5sft3dvtsfhdm unique (task);
create table task (id integer generated by default as identity, name varchar(255) not null, primary key (id));
alter table task add constraint UK_lerptdo9d67pejjpbfau899tm unique (name);
create table task (id integer generated by default as identity, name varchar(255) not null, primary key (id));
alter table task add constraint UK_lerptdo9d67pejjpbfau899tm unique (name);
